set_property PACKAGE_PIN Y16 [get_ports {rgb_out_0[2]}]
set_property PACKAGE_PIN Y17 [get_ports {rgb_out_0[1]}]
set_property PACKAGE_PIN R14 [get_ports {rgb_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb_out_0[0]}]
