set_property SRC_FILE_INFO {cfile:C:/Users/Jake/Engineering/ZYNQ/PS-AXI-GPIO/PS-AXI-GPIO.srcs/constrs_1/new/rgb.xdc rfile:../../../PS-AXI-GPIO.srcs/constrs_1/new/rgb.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {gpio_rtl_0_tri_io[2]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {gpio_rtl_0_tri_io[0]}]
