set_property SRC_FILE_INFO {cfile:C:/Users/Jake/Engineering/ZYNQ/PL-Interrupts/PL-Interrupts.srcs/constrs_1/new/switches.xdc rfile:../../../PL-Interrupts.srcs/constrs_1/new/switches.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R19 [get_ports {SW1[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T19 [get_ports {SW2[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {SW3[0]}]
