set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN Y16 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN Y17 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN R14 [get_ports {GPIO_0_0_tri_io[0]}]
